version: "3"

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: passwordDev
      POSTGRES_DB: easyreporting
    ports:
     - "5432:5432"
